apiVersion: v1
kind: Service
metadata:
    name: commercialhaskell
    labels:
        name: commercialhaskell
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3003
      protocol: TCP
    selector:
        name: commercialhaskell
